const mongoose = require('mongoose');

// Note model – central to the eNote app
const NoteSchema = new mongoose.Schema(
  {
    title: { type: String, required: true },
    // Store the HTML string generated by the ReactQuill editor
    content: { type: String, required: true },
    // Optional tags for categorisation / filtering (array of strings)
    tags: [{ type: String }],
    // Owner of the note – one of the three existing roles (Admin/Faculty/Student)
    createdBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },
    // Public sharing flag – false by default
    isPublic: { type: Boolean, default: false },
  },
  { timestamps: true }
);

NoteSchema.index({ title: 'text', content: 'text' });

module.exports = mongoose.model('Note', NoteSchema);
